# Generated by Django 5.2 on 2025-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=30)),
                ('avaliacao', models.FloatField(max_length=2)),
                ('rua', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('barro', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_motorista', models.CharField(max_length=11, unique=True)),
                ('data_nascimento_motorista', models.DateField()),
                ('veiculo', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=30)),
                ('cnh', models.CharField(max_length=11, unique=True)),
                ('numero_registro', models.CharField(max_length=11, unique=True)),
                ('senha_motorista', models.CharField(max_length=30)),
            ],
        ),
    ]
