# Generated by Django 5.2 on 2025-05-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0005_pedido_delete_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='pedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='content_app.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_entregues', to='content_app.motorista'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='content_app.cliente'),
        ),
    ]
