# Generated by Django 5.2 on 2025-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0006_pagamento_pedido_pedido_motorista_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.RemoveField(
            model_name='content',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(related_name='pedido', to='content_app.produto'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
