# Generated by Django 5.2 on 2025-06-03 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0007_delete_avaliacao_remove_content_creator_delete_loja_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='exemplo@email.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
