# Generated by Django 5.2 on 2025-06-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0008_cliente_email_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em_analise', 'Em Análise'), ('confirmado', 'Pedido Confirmado')], default='em_analise', max_length=20),
        ),
    ]
