# Generated by Django 5.2 on 2025-06-03 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0009_alter_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descricao',
            field=models.TextField(default='aaaaaaaaahhhhhhhhh'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='motorista',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_entregues', to='content_app.motorista'),
        ),
    ]
