# Generated by Django 5.2 on 2025-06-03 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0010_remove_pedido_produtos_alter_pedido_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_entregues', to='content_app.motorista'),
        ),
    ]
