# Generated by Django 5.2 on 2025-06-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0011_alter_pedido_motorista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
