# Generated by Django 5.2 on 2025-06-04 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0014_remove_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='content_app.cliente'),
            preserve_default=False,
        ),
    ]
