# Generated by Django 5.2 on 2025-06-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0015_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
