# Generated by Django 5.2 on 2025-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0018_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em_analise', 'Em Análise'), ('confirmado', 'Pedido Confirmado'), ('pago', 'Pago')], default='em_analise', max_length=20),
        ),
    ]
