# Generated by Django 5.2 on 2025-06-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0020_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em_analise', 'Em Análise'), ('confirmado', 'Pedido Confirmado'), ('pago', 'Pago'), ('pedido_enviado', 'Pedido Enviado'), ('entregue', 'Entregue')], default='em_analise', max_length=20),
        ),
    ]
