# Generated by Django 5.2 on 2025-06-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0021_alter_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
